name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Tests
        run: FOUNDRY_PROFILE=ci forge test

      - name: Publish ABIs
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            ./out/Multicall.sol/Multicall.json
            ./out/Multicall2.sol/Multicall2.json
            ./out/Multicall3.sol/Multicall3.json
